// libs/vortex-svelte/src/chat-message/ChatMessage.svelte
<!-- libs/vortex-svelte/src/chat-message/ChatMessage.svelte -->
<!-- Composed for vortex-ui on @ark-ui/svelte/factory; mirrored from @cloudvoyant/vortex-react ChatMessage -->
<script lang="ts">
  import { Ark } from '@ark-ui/svelte/factory';
  import { PaperclipIcon } from 'phosphor-svelte';
  import {
    chatMessageRowVariants,
    chatMessageContentVariants,
    chatMessageBubbleVariants,
    chatMessageMetaBase,
    chatMessageAuthorBase,
    chatMessageTimeBase,
    chatMessageAttachmentsBase,
    chatMessageAttachmentBase,
    cn,
  } from '@cloudvoyant/vortex-ui';
  import type {
    ChatMessageVariant,
    ChatMessageState,
    ChatReactions,
    ChatMessageAttachment,
  } from '@cloudvoyant/vortex-ui';
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';
  import { getChatLayout } from './ChatContext.svelte';
  import ChatMessageReactions from './ChatMessageReactions.svelte';

  type Props = {
    variant?: ChatMessageVariant;
    from?: string;
    at?: Date;
    state?: ChatMessageState;
    reactions?: ChatReactions;
    attachments?: ChatMessageAttachment[];
    class?: string;
    children?: Snippet;
  } & Omit<HTMLAttributes<HTMLDivElement>, 'from'>;

  let {
    variant = 'default',
    from,
    at,
    state = 'sent',
    reactions,
    attachments,
    class: className = '',
    children,
    ...rest
  }: Props = $props();

  const layout = getChatLayout();
  const showMeta = $derived(layout !== 'minimal' && Boolean(from || at));

  function formatTime(value?: Date): string {
    if (!value) return '';
    return value.toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' });
  }

  const rowClasses = $derived(cn(chatMessageRowVariants({ layout, variant }), className));
  const contentClasses = $derived(chatMessageContentVariants({ layout, variant }));
  const bubbleClasses = $derived(chatMessageBubbleVariants({ layout, variant, state }));
</script>

<Ark as="div" class={rowClasses} data-from={variant} data-state={state} {...rest}>
  <div class={contentClasses}>
    {#if showMeta}
      <div class={chatMessageMetaBase}>
        {#if from}<span class={chatMessageAuthorBase}>{from}</span>{/if}
        {#if at}<time class={chatMessageTimeBase}>{formatTime(at)}</time>{/if}
      </div>
    {/if}
    <div class={bubbleClasses} data-bubble>
      {@render children?.()}
    </div>
    {#if attachments && attachments.length > 0}
      <div class={chatMessageAttachmentsBase}>
        {#each attachments as a (a.id)}
          <div class={chatMessageAttachmentBase} data-attachment>
            <PaperclipIcon class="size-3.5" aria-hidden="true" />
            <span>{a.name}</span>
          </div>
        {/each}
      </div>
    {/if}
    {#if reactions}
      <ChatMessageReactions {reactions} />
    {/if}
  </div>
</Ark>

// libs/vortex-react/src/chat-message/ChatMessage.tsx
// libs/vortex-react/src/chat-message/ChatMessage.tsx
// Composed for vortex-ui on @ark-ui/react/factory; no upstream chat primitive.
import { ark, type HTMLArkProps } from '@ark-ui/react/factory';
import {
  chatMessageRowVariants,
  chatMessageContentVariants,
  chatMessageBubbleVariants,
  chatMessageMetaBase,
  chatMessageAuthorBase,
  chatMessageTimeBase,
  chatMessageAttachmentsBase,
  chatMessageAttachmentBase,
  cn,
} from '@cloudvoyant/vortex-ui';
import type { ChatMessageProps as ChatMessageBaseProps, ChatMessageAttachment } from '@cloudvoyant/vortex-ui';
import { PaperclipIcon } from '../chat-icons';
import { useChatLayout } from './ChatContext';
import { ChatMessageReactions } from './ChatMessageReactions';

export type ChatMessageProps = Omit<HTMLArkProps<'div'>, 'from'> & ChatMessageBaseProps;

function formatTime(at?: Date): string {
  if (!at) return '';
  return at.toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' });
}

export function ChatMessage({
  className,
  variant = 'default',
  from,
  at,
  state = 'sent',
  reactions,
  attachments,
  children,
  ...props
}: ChatMessageProps) {
  const layout = useChatLayout();
  const showMeta = layout !== 'minimal' && Boolean(from || at);
  return (
    <ark.div
      className={cn(chatMessageRowVariants({ layout, variant }), className)}
      data-from={variant}
      data-state={state}
      {...props}
    >
      <div className={chatMessageContentVariants({ layout, variant })}>
        {showMeta ? (
          <div className={chatMessageMetaBase}>
            {from ? <span className={chatMessageAuthorBase}>{from}</span> : null}
            {at ? <time className={chatMessageTimeBase}>{formatTime(at)}</time> : null}
          </div>
        ) : null}
        <div className={chatMessageBubbleVariants({ layout, variant, state })} data-bubble>
          {children}
        </div>
        {attachments && attachments.length > 0 ? (
          <div className={chatMessageAttachmentsBase}>
            {attachments.map((a: ChatMessageAttachment) => (
              <div key={a.id} className={chatMessageAttachmentBase} data-attachment>
                <PaperclipIcon className="size-3.5" aria-hidden="true" />
                <span>{a.name}</span>
              </div>
            ))}
          </div>
        ) : null}
        {reactions ? <ChatMessageReactions reactions={reactions} /> : null}
      </div>
    </ark.div>
  );
}
