// libs/vortex-react/src/chat/ChatThread.tsx
// libs/vortex-react/src/chat/ChatThread.tsx
// Composed for vortex-ui on @cloudvoyant/vortex-react Scroll; no upstream chat primitive.
import { useRef, type ReactNode, type UIEvent } from 'react';
import { Scroll } from '../scroll';
import { chatThreadBase, chatThreadContentBase, cn } from '@cloudvoyant/vortex-ui';

export interface ChatThreadProps {
  className?: string;
  contentClassName?: string;
  onScrollTop?: () => void;
  children?: ReactNode;
}

export function ChatThread({ className, contentClassName, onScrollTop, children }: ChatThreadProps) {
  const firedRef = useRef(false);
  const handleScroll = (e: UIEvent<HTMLDivElement>) => {
    const el = e.currentTarget;
    if (el.scrollTop <= 8) {
      if (!firedRef.current) {
        firedRef.current = true;
        onScrollTop?.();
      }
    } else {
      firedRef.current = false;
    }
  };
  return (
    <Scroll
      className={cn(chatThreadBase, className)}
      viewportClassName="flex h-full w-full flex-col"
      onScroll={onScrollTop ? handleScroll : undefined}
    >
      <div className={cn(chatThreadContentBase, contentClassName)} data-thread-content>
        {children}
      </div>
    </Scroll>
  );
}

// libs/vortex-svelte/src/chat/ChatThread.svelte
<!-- libs/vortex-svelte/src/chat/ChatThread.svelte -->
<!-- Composed for vortex-ui on @cloudvoyant/vortex-svelte Scroll; mirrored from @cloudvoyant/vortex-react ChatThread -->
<script lang="ts">
  import Scroll from '../Scroll.svelte';
  import { chatThreadBase, chatThreadContentBase, cn } from '@cloudvoyant/vortex-ui';
  import type { Snippet } from 'svelte';

  type Props = {
    class?: string;
    contentClass?: string;
    onScrollTop?: () => void;
    children?: Snippet;
  };

  let { class: className = '', contentClass = '', onScrollTop, children }: Props = $props();

  let fired = false;

  function handleScroll(e: Event) {
    const el = e.currentTarget as HTMLElement;
    if (el.scrollTop <= 8) {
      if (!fired) {
        fired = true;
        onScrollTop?.();
      }
    } else {
      fired = false;
    }
  }
</script>

<Scroll
  class={cn(chatThreadBase, className)}
  viewportClass="flex h-full w-full flex-col"
  onscroll={onScrollTop ? handleScroll : undefined}
>
  <div class={cn(chatThreadContentBase, contentClass)} data-thread-content>
    {@render children?.()}
  </div>
</Scroll>
