// libs/vortex-react/src/chat/Chat.tsx
// libs/vortex-react/src/chat/Chat.tsx
// Composed for vortex-ui on @ark-ui/react/factory; no upstream chat primitive.
import { ark, type HTMLArkProps } from '@ark-ui/react/factory';
import { chatRootBase, cn } from '@cloudvoyant/vortex-ui';
import type { ChatProps as ChatBaseProps } from '@cloudvoyant/vortex-ui';
import { ChatLayoutContext } from '../chat-message/ChatContext';

export type ChatProps = HTMLArkProps<'div'> & ChatBaseProps;

export function Chat({ className, layout = 'slack', children, ...props }: ChatProps) {
  return (
    <ChatLayoutContext.Provider value={layout}>
      <ark.div className={cn(chatRootBase, className)} data-layout={layout} {...props}>
        {children}
      </ark.div>
    </ChatLayoutContext.Provider>
  );
}

// libs/vortex-svelte/src/chat/Chat.svelte
<!-- libs/vortex-svelte/src/chat/Chat.svelte -->
<!-- Composed for vortex-ui on @ark-ui/svelte/factory; mirrored from @cloudvoyant/vortex-react Chat -->
<script lang="ts">
  import { Ark } from '@ark-ui/svelte/factory';
  import { chatRootBase, cn } from '@cloudvoyant/vortex-ui';
  import type { ChatLayout } from '@cloudvoyant/vortex-ui';
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';
  import { setChatLayout } from '../chat-message/ChatContext.svelte';

  type Props = {
    layout?: ChatLayout;
    class?: string;
    children?: Snippet;
  } & HTMLAttributes<HTMLDivElement>;

  let { layout = 'slack', class: className = '', children, ...rest }: Props = $props();

  setChatLayout(layout);

  const classes = $derived(cn(chatRootBase, className));
</script>

<Ark as="div" class={classes} data-layout={layout} {...rest}>
  {@render children?.()}
</Ark>
