// libs/vortex-svelte/src/chat/ChatInput.svelte
<!-- libs/vortex-svelte/src/chat/ChatInput.svelte -->
<!-- Composed for vortex-ui on @cloudvoyant/vortex-svelte Textarea + Button; mirrored from @cloudvoyant/vortex-react ChatInput -->
<script lang="ts">
  import { PaperclipIcon, PaperPlaneRightIcon as SendIcon, XIcon } from 'phosphor-svelte';
  import Textarea from '../Textarea.svelte';
  import Button from '../Button.svelte';
  import {
    chatInputRootBase,
    chatInputRowBase,
    chatInputTextareaBase,
    chatInputAttachmentsBase,
    chatInputAttachmentChipBase,
    chatInputAttachmentRemoveBase,
    chatInputAttachTriggerBase,
    cn,
  } from '@cloudvoyant/vortex-ui';
  import type { ChatMessageAttachment, ChatInputSubmit } from '@cloudvoyant/vortex-ui';

  type Props = {
    class?: string;
    placeholder?: string;
    disabled?: boolean;
    allowAttachments?: boolean;
    onSend?: (submit: ChatInputSubmit) => void;
  };

  let {
    class: className = '',
    placeholder = 'Type a message…',
    disabled = false,
    allowAttachments = true,
    onSend,
  }: Props = $props();

  let draft = $state('');
  let attachments = $state<ChatMessageAttachment[]>([]);
  let fileInput = $state<HTMLInputElement>();
  let seq = 0;

  const canSend = $derived(draft.trim().length > 0 || attachments.length > 0);

  function send() {
    const text = draft.trim();
    if (!text && attachments.length === 0) return;
    onSend?.({ text, attachments });
    draft = '';
    attachments = [];
  }

  function handleKeyDown(e: KeyboardEvent) {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      send();
    }
  }

  function handleFiles(e: Event) {
    const input = e.currentTarget as HTMLInputElement;
    const files = Array.from(input.files ?? []);
    attachments = [...attachments, ...files.map((f) => ({ id: `att-${++seq}`, name: f.name, size: f.size }))];
    input.value = '';
  }

  function removeAttachment(id: string) {
    attachments = attachments.filter((a) => a.id !== id);
  }
</script>

<div class={cn(chatInputRootBase, className)} data-chat-input>
  {#if attachments.length > 0}
    <div class={chatInputAttachmentsBase}>
      {#each attachments as a (a.id)}
        <span class={chatInputAttachmentChipBase} data-attachment>
          <PaperclipIcon class="size-3" aria-hidden="true" />
          {a.name}
          <button
            type="button"
            class={chatInputAttachmentRemoveBase}
            aria-label={`Remove ${a.name}`}
            onclick={() => removeAttachment(a.id)}
          >
            <XIcon class="size-3" aria-hidden="true" />
          </button>
        </span>
      {/each}
    </div>
  {/if}
  <div class={chatInputRowBase}>
    {#if allowAttachments}
      <button
        type="button"
        class={chatInputAttachTriggerBase}
        aria-label="Attach file"
        {disabled}
        onclick={() => fileInput?.click()}
      >
        <PaperclipIcon class="size-4" aria-hidden="true" />
      </button>
      <input bind:this={fileInput} type="file" multiple hidden onchange={handleFiles} data-file-input />
    {/if}
    <Textarea
      class={chatInputTextareaBase}
      {placeholder}
      value={draft}
      oninput={(e) => (draft = (e.currentTarget as HTMLTextAreaElement).value)}
      {disabled}
      rows={1}
      onkeydown={handleKeyDown}
      data-draft
    />
    <Button type="button" size="icon" aria-label="Send message" disabled={disabled || !canSend} onclick={send}>
      <SendIcon class="size-4" aria-hidden="true" />
    </Button>
  </div>
</div>

// libs/vortex-react/src/chat/ChatInput.tsx
// libs/vortex-react/src/chat/ChatInput.tsx
// Composed for vortex-ui on @cloudvoyant/vortex-react Textarea + Button; no upstream chat primitive.
import { useRef, useState, type ChangeEvent, type KeyboardEvent } from 'react';
import { PaperclipIcon, SendIcon, XIcon } from '../chat-icons';
import { Textarea } from '../textarea';
import { Button } from '../button';
import {
  chatInputRootBase,
  chatInputRowBase,
  chatInputTextareaBase,
  chatInputAttachmentsBase,
  chatInputAttachmentChipBase,
  chatInputAttachmentRemoveBase,
  chatInputAttachTriggerBase,
  cn,
} from '@cloudvoyant/vortex-ui';
import type { ChatMessageAttachment, ChatInputSubmit } from '@cloudvoyant/vortex-ui';

export interface ChatInputProps {
  className?: string;
  placeholder?: string;
  disabled?: boolean;
  allowAttachments?: boolean;
  onSend?: (submit: ChatInputSubmit) => void;
}

let attachmentSeq = 0;

export function ChatInput({
  className,
  placeholder = 'Type a message…',
  disabled = false,
  allowAttachments = true,
  onSend,
}: ChatInputProps) {
  const [draft, setDraft] = useState('');
  const [attachments, setAttachments] = useState<ChatMessageAttachment[]>([]);
  const fileRef = useRef<HTMLInputElement>(null);

  const send = () => {
    const text = draft.trim();
    if (!text && attachments.length === 0) return;
    onSend?.({ text, attachments });
    setDraft('');
    setAttachments([]);
  };

  const handleKeyDown = (e: KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      send();
    }
  };

  const handleFiles = (e: ChangeEvent<HTMLInputElement>) => {
    const files = Array.from(e.target.files ?? []);
    setAttachments((prev) => [
      ...prev,
      ...files.map((f) => ({ id: `att-${++attachmentSeq}`, name: f.name, size: f.size })),
    ]);
    e.target.value = '';
  };

  const removeAttachment = (id: string) => setAttachments((prev) => prev.filter((a) => a.id !== id));

  return (
    <div className={cn(chatInputRootBase, className)} data-chat-input>
      {attachments.length > 0 ? (
        <div className={chatInputAttachmentsBase}>
          {attachments.map((a) => (
            <span key={a.id} className={chatInputAttachmentChipBase} data-attachment>
              <PaperclipIcon className="size-3" aria-hidden="true" />
              {a.name}
              <button
                type="button"
                className={chatInputAttachmentRemoveBase}
                aria-label={`Remove ${a.name}`}
                onClick={() => removeAttachment(a.id)}
              >
                <XIcon className="size-3" aria-hidden="true" />
              </button>
            </span>
          ))}
        </div>
      ) : null}
      <div className={chatInputRowBase}>
        {allowAttachments ? (
          <>
            <button
              type="button"
              className={chatInputAttachTriggerBase}
              aria-label="Attach file"
              disabled={disabled}
              onClick={() => fileRef.current?.click()}
            >
              <PaperclipIcon className="size-4" aria-hidden="true" />
            </button>
            <input ref={fileRef} type="file" multiple hidden onChange={handleFiles} data-file-input />
          </>
        ) : null}
        <Textarea
          className={chatInputTextareaBase}
          placeholder={placeholder}
          value={draft}
          disabled={disabled}
          rows={1}
          onChange={(e) => setDraft(e.target.value)}
          onKeyDown={handleKeyDown}
          data-draft
        />
        <Button
          type="button"
          size="icon"
          aria-label="Send message"
          disabled={disabled || (!draft.trim() && attachments.length === 0)}
          onClick={send}
        >
          <SendIcon className="size-4" aria-hidden="true" />
        </Button>
      </div>
    </div>
  );
}
