// libs/vortex-react/src/editor/ImageInput.tsx
// libs/vortex-react/src/editor/ImageInput.tsx
// React parity of ImageInput.svelte. The app-specific uploader is replaced by the injected
// `onUpload` seam, with the URL tab as the fallback when no handler is supplied.
import { useEffect, useRef, useState } from 'react';
import type { Editor } from '@tiptap/react';
import type { ImageUploadResult } from '@cloudvoyant/vortex-ui';
import { X } from 'lucide-react';
import { ImageFileUpload } from './ImageFileUpload';

function fileToDataUrl(file: File): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () =>
      typeof reader.result === 'string' ? resolve(reader.result) : reject(new Error('No image data'));
    reader.onerror = () => reject(reader.error ?? new Error('Could not read image'));
    reader.readAsDataURL(file);
  });
}

export interface ImageInputProps {
  editor: Editor;
  position: number;
  onClose: () => void;
  /** Seam: replaces the source editor's app-specific uploader. */
  onUpload?: (file: File) => Promise<ImageUploadResult>;
}

export function ImageInput({ editor, position, onClose, onUpload }: ImageInputProps) {
  const [tab, setTab] = useState<'upload' | 'url'>('upload');
  const [urlValue, setUrlValue] = useState('');
  const [urlError, setUrlError] = useState('');
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [uploading, setUploading] = useState(false);
  const [uploadError, setUploadError] = useState('');
  const urlInputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (tab === 'url') urlInputRef.current?.focus();
  }, [tab]);

  function insertImage(src: string, srcset?: string) {
    editor.chain().focus().setTextSelection(position).insertImage({ src, srcset, alt: '', caption: '' }).run();
    onClose();
  }

  async function handleUpload() {
    if (!selectedFile) return setUploadError('Choose an image first.');
    setUploading(true);
    setUploadError('');
    try {
      const result: ImageUploadResult = onUpload
        ? await onUpload(selectedFile)
        : { src: await fileToDataUrl(selectedFile) };
      insertImage(result.src, result.srcset);
    } catch {
      setUploadError('Upload failed. Please try again.');
    } finally {
      setUploading(false);
    }
  }

  function handleUrlSubmit() {
    const trimmed = urlValue.trim();
    if (!trimmed) return setUrlError('Please enter a URL');
    try {
      new URL(trimmed);
    } catch {
      return setUrlError('Please enter a valid URL');
    }
    insertImage(trimmed);
  }

  return (
    <div
      role="dialog"
      aria-label="Insert image"
      tabIndex={-1}
      onKeyDown={(event) => {
        if (event.key === 'Escape') onClose();
      }}
      className="max-h-[calc(100vh-2rem)] w-80 overflow-y-auto rounded-lg border border-border bg-popover p-3 text-popover-foreground shadow-xl"
    >
      <div className="space-y-3">
        <div className="flex items-center justify-between">
          <p className="text-sm font-semibold">Insert Image</p>
          <button
            type="button"
            onClick={onClose}
            className="rounded p-1 text-muted-foreground hover:bg-muted hover:text-foreground"
            aria-label="Close image dialog"
          >
            <X className="size-4" />
          </button>
        </div>

        <div className="flex gap-1 rounded-md bg-muted p-1">
          {(['upload', 'url'] as const).map((value) => (
            <button
              key={value}
              type="button"
              onClick={() => {
                setTab(value);
                setUrlError('');
              }}
              className={`flex-1 rounded px-3 py-1 text-xs font-medium transition-colors ${
                tab === value ? 'bg-background shadow-sm' : 'text-muted-foreground hover:text-foreground'
              }`}
            >
              {value === 'upload' ? 'Upload' : 'URL'}
            </button>
          ))}
        </div>

        {tab === 'upload' ? (
          <div className="space-y-2">
            <ImageFileUpload
              file={selectedFile}
              disabled={uploading}
              onFileChange={(file) => {
                setSelectedFile(file);
                setUploadError('');
              }}
            />
            {uploading ? <p className="text-xs text-muted-foreground">Uploading…</p> : null}
            {uploadError ? <p className="text-xs text-destructive">{uploadError}</p> : null}
          </div>
        ) : (
          <div className="space-y-2">
            <input
              ref={urlInputRef}
              type="url"
              value={urlValue}
              onChange={(event) => {
                setUrlValue(event.target.value);
                setUrlError('');
              }}
              onKeyDown={(event) => {
                if (event.key === 'Enter') handleUrlSubmit();
              }}
              placeholder="https://example.com/image.jpg"
              className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm placeholder:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-ring"
            />
            {urlError ? <p className="text-xs text-destructive">{urlError}</p> : null}
          </div>
        )}

        <div className="flex justify-end gap-2">
          <button type="button" onClick={onClose} className="rounded-md px-3 py-1.5 text-sm hover:bg-muted">
            Cancel
          </button>
          <button
            type="button"
            onClick={tab === 'upload' ? () => void handleUpload() : handleUrlSubmit}
            disabled={uploading || (tab === 'upload' && !selectedFile)}
            className="rounded-md bg-primary px-3 py-1.5 text-sm font-medium text-primary-foreground hover:bg-primary/90 disabled:cursor-not-allowed disabled:opacity-50"
          >
            {tab === 'upload' ? (uploading ? 'Uploading…' : 'Upload') : 'Insert'}
          </button>
        </div>
      </div>
    </div>
  );
}

// libs/vortex-svelte/src/editor/ImageInput.svelte
<script lang="ts">
  import type { Editor } from '@tiptap/core';
  import type { ImageUploadResult } from '@cloudvoyant/vortex-ui';
  import { X } from 'lucide-svelte';
  import ImageFileUpload from './ImageFileUpload.svelte';

  interface Props {
    editor: Editor;
    position: number;
    onClose: () => void;
    /** Seam: replaces the source editor's app-specific uploader (was @readership/ui). */
    onUpload?: (file: File) => Promise<ImageUploadResult>;
  }

  let { editor, position, onClose, onUpload }: Props = $props();

  let activeTab = $state<'upload' | 'url'>('upload');
  let urlValue = $state('');
  let urlError = $state('');
  let urlInputEl: HTMLInputElement | undefined = $state();
  let selectedFile = $state<File | null>(null);
  let uploading = $state(false);
  let uploadError = $state('');

  $effect(() => {
    if (activeTab === 'url') {
      urlInputEl?.focus();
    }
  });

  function insertImage(src: string, srcset?: string) {
    editor.chain().focus().setTextSelection(position).insertImage({ src, srcset, alt: '', caption: '' }).run();
    onClose();
  }

  function fileToDataUrl(file: File): Promise<string> {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () =>
        typeof reader.result === 'string' ? resolve(reader.result) : reject(new Error('No image data'));
      reader.onerror = () => reject(reader.error ?? new Error('Could not read image'));
      reader.readAsDataURL(file);
    });
  }

  async function handleUpload() {
    if (!selectedFile) {
      uploadError = 'Choose an image first.';
      return;
    }

    uploading = true;
    uploadError = '';
    try {
      const result: ImageUploadResult = onUpload
        ? await onUpload(selectedFile)
        : { src: await fileToDataUrl(selectedFile) };
      insertImage(result.src, result.srcset);
    } catch {
      uploadError = 'Upload failed. Please try again.';
    } finally {
      uploading = false;
    }
  }

  function handleUrlSubmit() {
    const trimmed = urlValue.trim();
    if (!trimmed) {
      urlError = 'Please enter a URL';
      return;
    }
    try {
      new URL(trimmed);
    } catch {
      urlError = 'Please enter a valid URL';
      return;
    }
    insertImage(trimmed);
  }

  function handleKeydown(e: KeyboardEvent) {
    if (e.key === 'Escape') onClose();
  }

  function handleUrlKeydown(e: KeyboardEvent) {
    if (e.key === 'Enter') handleUrlSubmit();
  }
</script>

<!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
<div
  class="max-h-[calc(100vh-2rem)] w-80 overflow-y-auto rounded-lg border border-border bg-popover p-3 text-popover-foreground shadow-xl"
  role="dialog"
  aria-label="Insert image"
  tabindex="-1"
  onkeydown={handleKeydown}
>
  <div class="space-y-3">
    <div class="flex items-center justify-between">
      <p class="text-sm font-semibold">Insert Image</p>
      <button
        type="button"
        onclick={onClose}
        class="rounded p-1 text-muted-foreground hover:bg-muted hover:text-foreground"
        aria-label="Close image dialog"
      >
        <X size={16} />
      </button>
    </div>

    <!-- Tabs -->
    <div class="flex gap-1 rounded-md bg-muted p-1">
      <button
        type="button"
        onclick={() => {
          activeTab = 'upload';
          urlError = '';
        }}
        class="flex-1 rounded px-3 py-1 text-xs font-medium transition-colors {activeTab === 'upload'
          ? 'bg-background shadow-sm'
          : 'text-muted-foreground hover:text-foreground'}"
      >
        Upload
      </button>
      <button
        type="button"
        onclick={() => {
          activeTab = 'url';
          urlError = '';
        }}
        class="flex-1 rounded px-3 py-1 text-xs font-medium transition-colors {activeTab === 'url'
          ? 'bg-background shadow-sm'
          : 'text-muted-foreground hover:text-foreground'}"
      >
        URL
      </button>
    </div>

    {#if activeTab === 'upload'}
      <div class="space-y-2">
        <ImageFileUpload
          file={selectedFile}
          disabled={uploading}
          onFileChange={(file) => {
            selectedFile = file;
            uploadError = '';
          }}
        />
        {#if uploading}
          <p class="text-xs text-muted-foreground">Uploading…</p>
        {/if}
        {#if uploadError}
          <p class="text-xs text-destructive">{uploadError}</p>
        {/if}
      </div>
    {:else}
      <div class="space-y-2">
        <input
          type="url"
          bind:this={urlInputEl}
          bind:value={urlValue}
          onkeydown={handleUrlKeydown}
          oninput={() => {
            urlError = '';
          }}
          placeholder="https://example.com/image.jpg"
          class="w-full rounded-md border border-input bg-background px-3 py-2 text-sm placeholder:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-ring"
        />
        {#if urlError}
          <p class="text-xs text-destructive">{urlError}</p>
        {/if}
      </div>
    {/if}

    <div class="flex justify-end gap-2">
      <button type="button" onclick={onClose} class="rounded-md px-3 py-1.5 text-sm transition-colors hover:bg-muted">
        Cancel
      </button>
      <button
        type="button"
        onclick={activeTab === 'upload' ? handleUpload : handleUrlSubmit}
        disabled={uploading || (activeTab === 'upload' && !selectedFile)}
        class="rounded-md bg-primary px-3 py-1.5 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90 disabled:cursor-not-allowed disabled:opacity-50"
      >
        {activeTab === 'upload' ? (uploading ? 'Uploading…' : 'Upload') : 'Insert'}
      </button>
    </div>
  </div>
</div>
