// libs/vortex-react/src/editor/LinkEditPopover.tsx
// libs/vortex-react/src/editor/LinkEditPopover.tsx
// React parity of LinkEditPopover.svelte. Kept inside BubbleMenu's positioned surface so editing
// a link never invokes the browser's blocking, unstyleable window.prompt dialog.
import { useEffect, useRef, useState } from 'react';
import type { Editor } from '@tiptap/react';
import { ExternalLink, Globe, Trash2 } from 'lucide-react';

export interface LinkEditPopoverProps {
  editor: Editor;
  initialUrl?: string;
  onClose: () => void;
}

function safeExternalUrl(value: string): string | undefined {
  try {
    const url = new URL(value);
    return url.protocol === 'http:' || url.protocol === 'https:' ? url.href : undefined;
  } catch {
    return undefined;
  }
}

export function LinkEditPopover({ editor, initialUrl = '', onClose }: LinkEditPopoverProps) {
  const [url, setUrl] = useState(initialUrl);
  const inputRef = useRef<HTMLInputElement>(null);
  const externalUrl = safeExternalUrl(url.trim());

  useEffect(() => {
    setUrl(initialUrl);
    inputRef.current?.focus();
  }, [initialUrl]);

  function save() {
    const href = url.trim();
    if (href) editor.chain().focus().setLink({ href }).run();
    else editor.chain().focus().unsetLink().run();
    onClose();
  }

  function remove() {
    editor.chain().focus().unsetLink().run();
    onClose();
  }

  return (
    <div
      role="dialog"
      aria-label="Edit link"
      className="absolute start-0 top-full z-10 mt-2 flex w-72 items-center gap-2 rounded-md border border-border bg-popover px-2 py-1.5 text-popover-foreground shadow-lg"
      onKeyDown={(event) => {
        if (event.key === 'Enter') {
          event.preventDefault();
          save();
        }
        if (event.key === 'Escape') {
          event.preventDefault();
          onClose();
        }
      }}
    >
      <Globe className="size-4 shrink-0 text-muted-foreground" aria-hidden="true" />
      <input
        ref={inputRef}
        type="url"
        value={url}
        onChange={(event) => setUrl(event.target.value)}
        placeholder="https://example.com"
        className="min-w-0 flex-1 bg-transparent px-1 py-1 text-sm outline-none placeholder:text-muted-foreground"
      />
      <button
        type="button"
        onClick={remove}
        className="rounded p-1 text-muted-foreground hover:bg-accent hover:text-accent-foreground"
        aria-label="Remove link"
        title="Remove link"
      >
        <Trash2 className="size-4" />
      </button>
      {externalUrl ? (
        <a
          href={externalUrl}
          target="_blank"
          rel="noopener noreferrer"
          className="rounded p-1 text-muted-foreground hover:bg-accent hover:text-accent-foreground"
          aria-label="Open link in new tab"
          title="Open link in new tab"
        >
          <ExternalLink className="size-4" />
        </a>
      ) : null}
    </div>
  );
}

// libs/vortex-svelte/src/editor/LinkEditPopover.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import type { Editor } from '@tiptap/core';
  import { Trash2, Globe, ExternalLink } from 'lucide-svelte';

  interface Props {
    editor: Editor;
    initialUrl?: string;
    onClose: () => void;
  }

  let { editor, initialUrl = '', onClose }: Props = $props();

  let linkUrl = $derived(initialUrl);
  let inputElement: HTMLInputElement;
  let isFocused = $state(false);

  function saveAndClose() {
    if (linkUrl.trim()) {
      editor.chain().focus().setLink({ href: linkUrl.trim() }).run();
    } else {
      // If empty, remove the link
      editor.chain().focus().unsetLink().run();
    }
    onClose();
  }

  function removeLink() {
    editor.chain().focus().unsetLink().run();
    onClose();
  }

  function handleKeydown(event: KeyboardEvent) {
    if (event.key === 'Enter' || event.key === 'Escape') {
      event.preventDefault();
      saveAndClose();
    }
  }

  function handleBlur() {
    isFocused = false;
    // Small delay to allow clicking trash button
    setTimeout(saveAndClose, 100);
  }
</script>

<div
  class="fixed z-50 rounded border shadow-lg bg-popover text-popover-foreground"
  class:border-border={!isFocused}
  class:border-ring={isFocused}
  style="width: 280px"
>
  <div class="flex items-center gap-2 px-2">
    <span class="text-foreground/60 flex-shrink-0">
      <Globe size={16} />
    </span>
    <input
      bind:this={inputElement}
      type="text"
      bind:value={linkUrl}
      placeholder="Enter URL"
      class="flex-1 px-1.5 my-1 text-sm outline-none border-none rounded"
      class:bg-muted={!isFocused}
      class:bg-background={isFocused}
      style="padding-top: 0.25rem !important; padding-bottom: 0.25rem !important;"
      onkeydown={handleKeydown}
      onfocus={() => (isFocused = true)}
      onblur={handleBlur}
    />
    <button
      type="button"
      class="rounded p-1 hover:bg-accent hover:text-accent-foreground text-foreground/60 hover:text-foreground flex-shrink-0"
      onclick={removeLink}
      title="Remove link"
    >
      <Trash2 size={16} />
    </button>
    {#if linkUrl}
      <a
        href={linkUrl}
        target="_blank"
        rel="noopener noreferrer"
        class="rounded p-1 hover:bg-accent hover:text-accent-foreground text-foreground/60 hover:text-foreground flex-shrink-0"
        title="Open in new tab"
      >
        <ExternalLink size={16} />
      </a>
    {/if}
  </div>
</div>
