// libs/vortex-svelte/src/editor/Editor.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { Editor, type EditorOptions } from '@tiptap/core';
  import { SvelteNodeViewRenderer } from 'svelte-tiptap';
  import {
    buildExtensions,
    registerImageInsertCallback,
    unregisterImageInsertCallback,
    type SlashCommandItem,
    type MentionItem,
    type MentionListElement,
    type EmojiItem,
    type EditorCounts,
    type ImageUploadResult,
  } from '@cloudvoyant/vortex-ui';
  import BubbleMenuContent from './BubbleMenu.svelte';
  import SlashMenu from './SlashMenu.svelte';
  import BookmarkInput from './BookmarkInput.svelte';
  import ImageInput from './ImageInput.svelte';
  import YouTubeInput from './YouTubeInput.svelte';
  import PasteMenu from './PasteMenu.svelte';
  import ImageNodeView from './ImageNodeView.svelte';
  import UrlMentionPill from './UrlMentionPill.svelte';
  import LinkPreviewCard from './LinkPreviewCard.svelte';
  import CodeBlockComponent from './CodeBlockComponent.svelte';
  import NoticeNodeView from './NoticeNodeView.svelte';
  import MermaidNodeView from './MermaidNodeView.svelte';
  import MentionList from './MentionList.svelte';
  import EmojiList from './EmojiList.svelte';
  import type { SuggestionProps } from '@tiptap/suggestion';
  import type { JSONContent } from '@tiptap/core';

  let {
    content = '',
    editable = true,
    onchange,
    mentionSource,
    hrefBuilder,
    onUpload,
  }: {
    content?: string;
    editable?: boolean;
    onchange?: (data: { content: string; title: string }) => void;
    /** Seam: replaces the source editor's hardcoded internal-search endpoint. */
    mentionSource?: (query: string) => Promise<MentionItem[]>;
    /** Seam: replaces the source editor's hardcoded /read/... hrefs. */
    hrefBuilder?: (item: MentionItem) => string;
    /** Seam: replaces the source editor's app-specific image upload. */
    onUpload?: (file: File) => Promise<ImageUploadResult>;
  } = $props();

  let editor = $state<Editor | null>(null);
  let element: HTMLDivElement;
  let slashMenuProps = $state<SuggestionProps<SlashCommandItem> | null>(null);
  // The mention menu renders from the template (like the slash menu) rather than being mounted
  // into document.body: that is the pattern already proven to work in this component, and it
  // keeps keydown delegation on a bound element instead of a detached mount.
  let mentionMenuProps = $state<SuggestionProps<MentionItem> | null>(null);
  let mentionMenuCoords = $state({ left: 0, top: 0 });
  let mentionMenuEl = $state<HTMLElement | null>(null);
  // Emoji picker: same template-render pattern. Without a render, `:` silently does nothing.
  let emojiMenuProps = $state<SuggestionProps<EmojiItem> | null>(null);
  let emojiMenuCoords = $state({ left: 0, top: 0 });
  let emojiMenuEl = $state<HTMLElement | null>(null);
  let slashMenuCoords = $state({ left: 0, top: 0 });
  let bookmarkInputActive = $state(false);
  let bookmarkInputPosition = $state(0);
  let bookmarkInputCoords = $state({ left: 0, top: 0 });
  let imageInputActive = $state(false);
  let imageInputPosition = $state(0);
  let imageInputCoords = $state({ left: 0, top: 0 });
  let youTubeInputActive = $state(false);
  let youTubeInputPosition = $state(0);
  let youTubeInputCoords = $state({ left: 0, top: 0 });
  let pasteMenuActive = $state(false);
  let pasteMenuUrl = $state('');
  let pasteMenuPosition = $state(0);
  let pasteMenuCoords = $state({ left: 0, top: 0 });

  type SlashCommandInsertStorage = {
    slashCommands: { onInsertYouTube?: (position: number) => void };
  };

  function registerYouTubeInsert(editorInstance: Editor, callback: (position: number) => void) {
    // SAFETY: the shared slashCommands extension owns this per-editor storage object and
    // initializes `onInsertYouTube`; Tiptap exposes extension storage as an open bag.
    (editorInstance.storage as unknown as SlashCommandInsertStorage).slashCommands.onInsertYouTube = callback;
  }

  function unregisterYouTubeInsert(editorInstance: Editor) {
    // SAFETY: same extension-owned storage invariant as registerYouTubeInsert.
    (editorInstance.storage as unknown as SlashCommandInsertStorage).slashCommands.onInsertYouTube = undefined;
  }

  function findScrollableAncestor(element: HTMLElement): HTMLElement | null {
    let current = element.parentElement;
    while (current && current !== document.body) {
      const overflowY = window.getComputedStyle(current).overflowY;
      if (/(auto|scroll)/.test(overflowY) && current.scrollHeight > current.clientHeight) return current;
      current = current.parentElement;
    }
    return null;
  }

  function updateSlashMenuPosition() {
    const props = slashMenuProps;
    if (!props) return;
    const rect = props.clientRect?.();
    if (!rect || rect.left === undefined || rect.top === undefined) return;

    const itemCount = props.items?.length || 0;
    const menuHeight = Math.min(itemCount * 36 + 8, 320);
    const spaceBelow = window.innerHeight - rect.bottom;
    const top = spaceBelow < menuHeight && rect.top > spaceBelow ? rect.top - menuHeight - 8 : rect.bottom + 8;
    slashMenuCoords = { left: rect.left, top };
  }

  // Reposition on every suggestion update and while any ancestor scrolls, so a fixed menu remains
  // attached to the slash cursor rather than being left behind in the viewport.
  $effect(() => {
    if (slashMenuProps) updateSlashMenuPosition();
  });

  $effect(() => {
    if (!slashMenuProps) return;
    window.addEventListener('scroll', updateSlashMenuPosition, true);
    window.addEventListener('resize', updateSlashMenuPosition);
    return () => {
      window.removeEventListener('scroll', updateSlashMenuPosition, true);
      window.removeEventListener('resize', updateSlashMenuPosition);
    };
  });

  // Lock only the editor's nearest scroll viewport while the slash menu is open. Page scrolling
  // remains available outside that viewport.
  $effect(() => {
    const activeMenu = slashMenuProps;
    const editorInstance = editor;
    if (!activeMenu || !editorInstance) return;
    const container = findScrollableAncestor(editorInstance.view.dom);
    if (!container) return;
    const preventWheel = (event: WheelEvent) => event.preventDefault();
    container.addEventListener('wheel', preventWheel, { passive: false });
    return () => container.removeEventListener('wheel', preventWheel);
  });

  // Extract title from content (first H1)
  function extractTitle(json: JSONContent): string {
    if (json && json.content && json.content[0]?.type === 'heading' && json.content[0]?.attrs?.level === 1) {
      return json.content[0]?.content?.[0]?.text || '';
    }
    return '';
  }

  onMount(() => {
    // Cleanup any existing editor first (helps with hot reload)
    if (editor) {
      editor.destroy();
      editor = null;
    }

    const nodeViews = {
      image: () => SvelteNodeViewRenderer(ImageNodeView),
      urlMention: () => SvelteNodeViewRenderer(UrlMentionPill),
      linkPreview: () => SvelteNodeViewRenderer(LinkPreviewCard),
      codeBlock: () => SvelteNodeViewRenderer(CodeBlockComponent),
      notice: () => SvelteNodeViewRenderer(NoticeNodeView),
      mermaid: () => SvelteNodeViewRenderer(MermaidNodeView),
    };

    editor = new Editor({
      element,
      ...({ immediatelyRender: false } as unknown as Partial<EditorOptions>),
      extensions: buildExtensions({
        mentionSource,
        hrefBuilder,
        nodeViews,
        mentionRender: () => ({
          onStart: (props: SuggestionProps<MentionItem>) => {
            mentionMenuProps = props;
            const rect = props.clientRect?.();
            if (rect) mentionMenuCoords = { left: rect.left, top: rect.bottom + 8 };
          },
          onUpdate: (props: SuggestionProps<MentionItem>) => {
            mentionMenuProps = props;
            const rect = props.clientRect?.();
            if (rect) mentionMenuCoords = { left: rect.left, top: rect.bottom + 8 };
          },
          onKeyDown: (props: { event: KeyboardEvent }) => {
            if (props.event.key === 'Escape') {
              props.event.preventDefault();
              props.event.stopPropagation();
              return true;
            }
            // MentionList exposes its handler on the element (see its $effect).
            const child = mentionMenuEl?.firstElementChild as MentionListElement | null;
            return child?.__mentionListKeyDown?.(props.event) ?? false;
          },
          onExit: () => {
            mentionMenuProps = null;
          },
        }),
        // The slash menu is rendered from this component's template (see `slashMenuProps`).
        emojiRender: () => ({
          onStart: (props: SuggestionProps<EmojiItem>) => {
            emojiMenuProps = props;
            const rect = props.clientRect?.();
            if (rect) emojiMenuCoords = { left: rect.left, top: rect.bottom + 8 };
          },
          onUpdate: (props: SuggestionProps<EmojiItem>) => {
            emojiMenuProps = props;
            const rect = props.clientRect?.();
            if (rect) emojiMenuCoords = { left: rect.left, top: rect.bottom + 8 };
          },
          onKeyDown: (props: { event: KeyboardEvent }) => {
            if (props.event.key === 'Escape') {
              props.event.preventDefault();
              props.event.stopPropagation();
              return true;
            }
            const child = emojiMenuEl?.firstElementChild as MentionListElement | null;
            return child?.__mentionListKeyDown?.(props.event) ?? false;
          },
          onExit: () => {
            emojiMenuProps = null;
          },
        }),
        slashRender: () => ({
          onStart: (props: SuggestionProps<SlashCommandItem>) => {
            slashMenuProps = props;
          },
          onUpdate: (props: SuggestionProps<SlashCommandItem>) => {
            slashMenuProps = props;
          },
          onExit: () => {
            slashMenuProps = null;
          },
        }),
      }),
      content: content
        ? JSON.parse(content)
        : {
            type: 'doc',
            content: [
              {
                type: 'heading',
                attrs: { level: 1 },
                content: [],
              },
              {
                type: 'paragraph',
                content: [],
              },
            ],
          },
      editable,
      onUpdate: ({ editor }) => {
        const json = editor.getJSON();
        const title = extractTitle(json);
        const contentStr = JSON.stringify(json);
        onchange?.({ content: contentStr, title });
      },
      editorProps: {
        attributes: {
          class: 'prose prose-lg focus:outline-none max-w-none min-h-[500px]',
        },
        handlePaste: (view, event) => {
          // Get pasted text
          const text = event.clipboardData?.getData('text/plain') || '';

          // Check if it's a URL
          const urlRegex = /^https?:\/\/.+/i;
          if (!urlRegex.test(text.trim())) {
            return false; // Let default paste behavior handle it
          }

          // Prevent default paste
          event.preventDefault();

          // Get current position
          const { from } = view.state.selection;

          // Insert URL text temporarily
          editor?.chain().focus().insertContent(text).run();

          // Calculate position for paste menu with flip logic
          const coords = view.coordsAtPos(from);
          const menuHeight = 150; // approximate height of paste menu
          const spaceBelow = window.innerHeight - coords.bottom;
          const spaceAbove = coords.top;

          const top =
            spaceBelow < menuHeight && spaceAbove > spaceBelow ? coords.top - menuHeight - 8 : coords.bottom + 8;

          pasteMenuCoords = {
            left: coords.left,
            top,
          };

          // Show paste menu
          pasteMenuUrl = text.trim();
          pasteMenuPosition = from;
          pasteMenuActive = true;

          return true; // Handled
        },
      },
    });

    // Register callback so the image slash command can directly set Svelte state
    // (editor.storage mutations are not tracked by Svelte 5 $effect)
    registerImageInsertCallback(editor!, (position) => {
      const coords = editor!.view.coordsAtPos(position);
      const panelHeight = 480;
      const viewportGap = 16;
      const spaceBelow = window.innerHeight - coords.bottom;
      const spaceAbove = coords.top;
      const preferredTop =
        spaceBelow < panelHeight && spaceAbove > spaceBelow ? coords.top - panelHeight - 8 : coords.bottom + 8;
      const top = Math.min(
        Math.max(preferredTop, viewportGap),
        Math.max(window.innerHeight - panelHeight - viewportGap, viewportGap),
      );
      imageInputCoords = { left: coords.left, top };
      imageInputPosition = position;
      imageInputActive = true;
    });

    registerYouTubeInsert(editor!, (position: number) => {
      const coords = editor!.view.coordsAtPos(position);
      youTubeInputCoords = { left: coords.left, top: coords.bottom + 8 };
      youTubeInputPosition = position;
      youTubeInputActive = true;
    });
  });

  interface BookmarkInputState {
    active: boolean;
    position: number;
  }

  function isBookmarkInputState(v: unknown): v is BookmarkInputState {
    return typeof v === 'object' && v !== null && 'active' in v;
  }

  // Watch for bookmark input trigger
  $effect(() => {
    if (!editor?.view) return;

    const storage = editor.storage as unknown as Record<string, unknown>;
    const bookmarkInput = storage['bookmarkInput'];
    if (isBookmarkInputState(bookmarkInput) && bookmarkInput.active) {
      const pos = bookmarkInput.position;
      bookmarkInputPosition = pos;

      // Calculate position using coordsAtPos
      const coords = editor.view.coordsAtPos(pos);
      bookmarkInputCoords = {
        left: coords.left,
        top: coords.bottom + 8,
      };

      bookmarkInputActive = true;

      // Reset the trigger
      storage['bookmarkInput'] = { active: false };
    }
  });

  onDestroy(() => {
    if (editor) {
      unregisterImageInsertCallback(editor);
      unregisterYouTubeInsert(editor);
      editor.destroy();
    }
  });

  // Update editable state
  $effect(() => {
    if (editor) {
      editor.setEditable(editable);
    }
  });

  // Expose method to update content externally
  export function updateContent(newContent: string) {
    if (editor && newContent !== JSON.stringify(editor.getJSON())) {
      try {
        const parsed = JSON.parse(newContent);
        editor.commands.setContent(parsed);
      } catch (e) {
        console.error('Failed to parse content:', e);
      }
    }
  }

  // Expose focus method
  export function focus() {
    if (editor) {
      editor.commands.focus('start');
    }
  }

  // Expose method to get analytics counts
  export function getCounts(): EditorCounts {
    if (!editor) {
      return { wordCount: 0, charCount: 0, pageCount: 0, readDuration: 0 };
    }

    const wordCount = editor.storage.characterCount?.words() || 0;
    const charCount = editor.storage.characterCount?.characters() || 0;
    const pageCount = Math.max(1, Math.ceil(wordCount / 300));
    const readDuration = Math.max(1, Math.ceil(wordCount / 250));

    return { wordCount, charCount, pageCount, readDuration };
  }
</script>

<div class="relative">
  <div bind:this={element}></div>
  {#if editor}
    <BubbleMenuContent {editor} />
    {#if slashMenuProps}
      <div class="fixed z-50" style="left: {slashMenuCoords.left}px; top: {slashMenuCoords.top}px;">
        <SlashMenu items={slashMenuProps.items || []} command={(item) => slashMenuProps?.command?.(item)} />
      </div>
    {/if}
    {#if mentionMenuProps}
      <div
        bind:this={mentionMenuEl}
        class="fixed z-50"
        style="left: {mentionMenuCoords.left}px; top: {mentionMenuCoords.top}px;"
      >
        <MentionList
          items={mentionMenuProps.items || []}
          command={(item) => mentionMenuProps?.command?.(item)}
          clientRect={mentionMenuProps.clientRect ?? null}
        />
      </div>
    {/if}
    {#if emojiMenuProps}
      <div
        bind:this={emojiMenuEl}
        class="fixed z-50"
        style="left: {emojiMenuCoords.left}px; top: {emojiMenuCoords.top}px;"
      >
        <EmojiList
          items={emojiMenuProps.items || []}
          command={(item) => emojiMenuProps?.command?.(item)}
          clientRect={emojiMenuProps.clientRect ?? null}
        />
      </div>
    {/if}
    {#if bookmarkInputActive}
      <div class="fixed z-50" style="left: {bookmarkInputCoords.left}px; top: {bookmarkInputCoords.top}px;">
        <BookmarkInput
          {editor}
          position={bookmarkInputPosition}
          onClose={() => {
            bookmarkInputActive = false;
          }}
        />
      </div>
    {/if}
    {#if imageInputActive}
      <div class="fixed z-50" style="left: {imageInputCoords.left}px; top: {imageInputCoords.top}px;">
        <ImageInput
          {editor}
          {onUpload}
          position={imageInputPosition}
          onClose={() => {
            imageInputActive = false;
          }}
        />
      </div>
    {/if}
    {#if youTubeInputActive}
      <div class="fixed z-50" style="left: {youTubeInputCoords.left}px; top: {youTubeInputCoords.top}px;">
        <YouTubeInput
          {editor}
          position={youTubeInputPosition}
          onClose={() => {
            youTubeInputActive = false;
          }}
        />
      </div>
    {/if}
    {#if pasteMenuActive}
      <div class="fixed z-50" style="left: {pasteMenuCoords.left}px; top: {pasteMenuCoords.top}px;">
        <PasteMenu
          {editor}
          url={pasteMenuUrl}
          position={pasteMenuPosition}
          onClose={() => {
            pasteMenuActive = false;
          }}
        />
      </div>
    {/if}
  {/if}
</div>

<style>
  /* Text alignment - applies to both editor and read view */
  :global([data-text-align='left']),
  :global(.ProseMirror [data-text-align='left']) {
    text-align: left !important;
  }

  :global([data-text-align='center']),
  :global(.ProseMirror [data-text-align='center']) {
    text-align: center !important;
  }

  :global([data-text-align='right']),
  :global(.ProseMirror [data-text-align='right']) {
    text-align: right !important;
  }

  :global([data-text-align='justify']),
  :global(.ProseMirror [data-text-align='justify']) {
    text-align: justify !important;
  }

  /* Text colors - theme-aware */
  :global(.ProseMirror span[data-color='red']) {
    color: var(--text-red);
  }
  :global(.ProseMirror span[data-color='orange']) {
    color: var(--text-orange);
  }
  :global(.ProseMirror span[data-color='yellow']) {
    color: var(--text-yellow);
  }
  :global(.ProseMirror span[data-color='green']) {
    color: var(--text-green);
  }
  :global(.ProseMirror span[data-color='cyan']) {
    color: var(--text-cyan);
  }
  :global(.ProseMirror span[data-color='blue']) {
    color: var(--text-blue);
  }
  :global(.ProseMirror span[data-color='violet']) {
    color: var(--text-violet);
  }
  :global(.ProseMirror span[data-color='fuchsia']) {
    color: var(--text-fuchsia);
  }
  :global(.ProseMirror span[data-color='slate']) {
    color: var(--text-slate);
  }

  /* Tiptap writes selected highlight colors inline. Keep only a non-important default so the
     chosen color remains authoritative. */
  :global(.ProseMirror mark) {
    background-color: var(--highlight-yellow);
    color: inherit !important;
  }

  /* Code block syntax highlighting */
  :global(.ProseMirror pre) {
    background-color: var(--code-block-bg);
    border-radius: 0.5rem;
    padding: 1rem;
    overflow-x: auto;
    font-family: 'JetBrains Mono', 'Fira Code', 'Monaco', 'Courier New', monospace;
    font-size: calc(var(--base-font-size, 16px) * 0.875);
    line-height: var(--line-height, 1.5);
    border: 1px solid var(--code-block-border, #e5e5e5);
  }

  :global(.ProseMirror pre code) {
    background: none;
    padding: 0;
    border-radius: 0;
    font-size: inherit;
    font-family: inherit;
  }

  /* ProseMirror container */
  :global(.ProseMirror) {
    position: relative;
  }

  /* List styling fixes */
  :global(.ProseMirror ul),
  :global(.ProseMirror ol) {
    padding-left: 1.25rem !important;
    margin: 1rem 0 !important;
  }

  :global(.ProseMirror li) {
    display: list-item !important;
    list-style-position: outside !important;
    margin: 0.25rem 0 !important;
    padding-left: 0.25rem !important;
  }

  :global(.ProseMirror ul > li) {
    list-style-type: disc !important;
  }

  :global(.ProseMirror ol > li) {
    list-style-type: decimal !important;
  }

  :global(.ProseMirror li p) {
    display: inline !important;
    margin: 0 !important;
  }

  :global(.ProseMirror ul[data-type='taskList']) {
    list-style-type: none !important;
    padding-left: 0 !important;
  }

  :global(.ProseMirror ul[data-type='taskList'] li) {
    display: flex !important;
    align-items: flex-start !important;
    gap: 0.5rem !important;
    list-style-type: none !important;
  }

  :global(.ProseMirror ul[data-type='taskList'] li > label) {
    flex-shrink: 0 !important;
    margin-top: 0.2rem !important;
  }

  :global(.ProseMirror ul[data-type='taskList'] li > div) {
    flex: 1 !important;
  }

  :global(.ProseMirror ul[data-type='taskList'] li p) {
    display: inline !important;
    margin: 0 !important;
  }

  /* Indent styles */
  :global(.ProseMirror .tt-indent-1) {
    margin-left: 2rem !important;
  }

  :global(.ProseMirror .tt-indent-2) {
    margin-left: 4rem !important;
  }

  :global(.ProseMirror .tt-indent-3) {
    margin-left: 6rem !important;
  }

  :global(.ProseMirror .tt-indent-4) {
    margin-left: 8rem !important;
  }

  :global(.ProseMirror .tt-indent-5) {
    margin-left: 10rem !important;
  }

  :global(.ProseMirror .tt-indent-6) {
    margin-left: 12rem !important;
  }

  :global(.ProseMirror .tt-indent-7) {
    margin-left: 14rem !important;
  }

  :global(.ProseMirror .tt-indent-8) {
    margin-left: 16rem !important;
  }

  /* Internal Mention - styled like regular links */
  :global(.ProseMirror a.internal-mention) {
    color: inherit;
    text-decoration: underline;
    cursor: text;
    user-select: text;
    -webkit-user-select: text;
  }

  :global(.ProseMirror a.internal-mention:hover) {
    opacity: 0.8;
  }

  /* URL Mention Pills in Editor */
  :global(.ProseMirror .url-mention-pill-edit) {
    background-color: var(--url-pill-bg);
  }

  :global(.ProseMirror .url-mention-pill-edit:hover) {
    background-color: var(--bookmark-bg-hover);
  }
</style>

// libs/vortex-react/src/editor/Editor.tsx
// libs/vortex-react/src/editor/Editor.tsx
// React parity of the Svelte Editor: same props, same seams, same Tiptap JSON contract.
// Consumes the framework-agnostic buildExtensions from vortex-ui and injects the React node
// views.
//
// Menu rendering mirrors the Svelte editor: the suggestion renders only track state here, and
// the menus are rendered from this component's JSX. That keeps them inside the framework tree
// (no duplicate mounts) and lets us position them from the suggestion's clientRect.
import { forwardRef, useCallback, useEffect, useImperativeHandle, useMemo, useRef, useState } from 'react';
import { useEditor, EditorContent, ReactNodeViewRenderer, type Editor as TiptapEditor } from '@tiptap/react';
import type { JSONContent } from '@tiptap/core';
import type { SuggestionKeyDownProps, SuggestionProps } from '@tiptap/suggestion';
import {
  buildExtensions,
  registerImageInsertCallback,
  unregisterImageInsertCallback,
  registerYouTubeInsertCallback,
  unregisterYouTubeInsertCallback,
  type EditorCounts,
  type MentionItem,
  type ImageUploadResult,
  type SlashCommandItem,
  type EmojiItem,
} from '@cloudvoyant/vortex-ui';
import { ImageNodeView } from './ImageNodeView';
import { UrlMentionPill } from './UrlMentionPill';
import { LinkPreviewCard } from './LinkPreviewCard';
import { CodeBlockComponent } from './CodeBlockComponent';
import { NoticeNodeView } from './NoticeNodeView';
import { MermaidNodeView } from './MermaidNodeView';
import { BubbleMenu } from './BubbleMenu';
import { SlashMenu, type SlashMenuHandle } from './SlashMenu';
import { MentionList, type MentionListHandle } from './MentionList';
import { EmojiList, type EmojiListHandle } from './EmojiList';
import { ImageInput } from './ImageInput';
import { BookmarkInput } from './BookmarkInput';
import { YouTubeInput } from './YouTubeInput';
import { PasteMenu } from './PasteMenu';

export interface EditorHandle {
  focus: () => void;
  updateContent: (json: string) => void;
  getCounts: () => EditorCounts;
}

export interface EditorProps {
  content?: string;
  editable?: boolean;
  onChange?: (data: { content: string; title: string }) => void;
  /** Seam: replaces the source editor's hardcoded internal-search endpoint. */
  mentionSource?: (query: string) => Promise<MentionItem[]>;
  /** Seam: replaces the source editor's hardcoded /read/... hrefs. */
  hrefBuilder?: (item: MentionItem) => string;
  /** Seam: replaces the source editor's app-specific image upload. */
  onUpload?: (file: File) => Promise<ImageUploadResult>;
}

function extractTitle(json: JSONContent): string {
  if (json?.content?.[0]?.type === 'heading' && json.content[0]?.attrs?.level === 1) {
    return json.content[0]?.content?.[0]?.text || '';
  }
  return '';
}

interface MenuState<T> {
  props: SuggestionProps<T> | null;
  coords: { left: number; top: number };
}

/** Shared counts, matching the Svelte editor (300 words/page, 250 words/minute). */
export function getEditorCounts(editor: TiptapEditor | null): EditorCounts {
  const words = editor?.storage.characterCount?.words() ?? 0;
  const chars = editor?.storage.characterCount?.characters() ?? 0;
  return {
    wordCount: words,
    charCount: chars,
    pageCount: Math.max(1, Math.ceil(words / 300)),
    readDuration: Math.max(1, Math.ceil(words / 250)),
  };
}

export const Editor = forwardRef<EditorHandle, EditorProps>(function Editor(
  { content = '', editable = true, onChange, mentionSource, hrefBuilder, onUpload },
  ref,
) {
  const [slash, setSlash] = useState<MenuState<SlashCommandItem>>({ props: null, coords: { left: 0, top: 0 } });
  const [mention, setMention] = useState<MenuState<MentionItem>>({ props: null, coords: { left: 0, top: 0 } });
  const [emoji, setEmoji] = useState<MenuState<EmojiItem>>({ props: null, coords: { left: 0, top: 0 } });

  const [imageInput, setImageInput] = useState<{ position: number; coords: { left: number; top: number } } | null>(
    null,
  );
  const [bookmarkInput, setBookmarkInput] = useState<{
    position: number;
    coords: { left: number; top: number };
  } | null>(null);
  const [youTubeInput, setYouTubeInput] = useState<{
    position: number;
    coords: { left: number; top: number };
  } | null>(null);
  const [pasteMenu, setPasteMenu] = useState<{
    url: string;
    position: number;
    coords: { left: number; top: number };
  } | null>(null);

  const slashRef = useRef<SlashMenuHandle>(null);
  const mentionRef = useRef<MentionListHandle>(null);
  const emojiRef = useRef<EmojiListHandle>(null);
  // The editor instance is created asynchronously by useEditor, so the paste handler (which is
  // bound at creation time) reads the menus' setters through refs.
  const menusRef = useRef({ setPasteMenu });

  const extensions = useMemo(
    () =>
      buildExtensions({
        mentionSource,
        hrefBuilder,
        nodeViews: {
          image: () => ReactNodeViewRenderer(ImageNodeView),
          urlMention: () => ReactNodeViewRenderer(UrlMentionPill),
          linkPreview: () => ReactNodeViewRenderer(LinkPreviewCard),
          codeBlock: () => ReactNodeViewRenderer(CodeBlockComponent),
          notice: () => ReactNodeViewRenderer(NoticeNodeView),
          mermaid: () => ReactNodeViewRenderer(MermaidNodeView),
        },
        // State-only renders; the menus are drawn from JSX below.
        mentionRender: () => ({
          onStart: (props: SuggestionProps<MentionItem>) => setMention(menuFrom(props)),
          onUpdate: (props: SuggestionProps<MentionItem>) => setMention(menuFrom(props)),
          onKeyDown: (props: SuggestionKeyDownProps) => mentionRef.current?.onKeyDown(props) ?? false,
          onExit: () => setMention({ props: null, coords: { left: 0, top: 0 } }),
        }),
        slashRender: () => ({
          onStart: (props: SuggestionProps<SlashCommandItem>) => setSlash(menuFrom(props)),
          onUpdate: (props: SuggestionProps<SlashCommandItem>) => setSlash(menuFrom(props)),
          onKeyDown: (props: SuggestionKeyDownProps) => slashRef.current?.onKeyDown(props) ?? false,
          onExit: () => setSlash({ props: null, coords: { left: 0, top: 0 } }),
        }),
        // Without an emoji render, typing ':' silently does nothing in either framework.
        emojiRender: () => ({
          onStart: (props: SuggestionProps<EmojiItem>) => setEmoji(menuFrom(props)),
          onUpdate: (props: SuggestionProps<EmojiItem>) => setEmoji(menuFrom(props)),
          onKeyDown: (props: SuggestionKeyDownProps) => emojiRef.current?.onKeyDown(props) ?? false,
          onExit: () => setEmoji({ props: null, coords: { left: 0, top: 0 } }),
        }),
      }),
    [mentionSource, hrefBuilder],
  );

  // Suggestion renders supply viewport coordinates. Recalculate them while the page or a nested
  // scroll container moves so the fixed menu stays attached to the slash cursor.
  useEffect(() => {
    if (!slash.props) return;
    const updatePosition = () =>
      setSlash((current) => (current.props ? menuFrom(current.props as SuggestionProps<SlashCommandItem>) : current));
    window.addEventListener('scroll', updatePosition, true);
    window.addEventListener('resize', updatePosition);
    return () => {
      window.removeEventListener('scroll', updatePosition, true);
      window.removeEventListener('resize', updatePosition);
    };
  }, [slash.props]);

  const editor = useEditor({
    extensions,
    editable,
    content: content
      ? JSON.parse(content)
      : {
          type: 'doc',
          content: [
            { type: 'heading', attrs: { level: 1 }, content: [] },
            { type: 'paragraph', content: [] },
          ],
        },
    onUpdate: ({ editor }) => {
      const json = editor.getJSON();
      onChange?.({ content: JSON.stringify(json), title: extractTitle(json) });
    },
    editorProps: {
      attributes: {
        class:
          'prose prose-lg min-h-[500px] max-w-none focus:outline-none [&_mark]:rounded-sm [&_mark]:bg-yellow-200 [&_mark]:px-0.5 dark:[&_mark]:bg-yellow-900/70',
      },
      // Pasting a bare URL opens the paste menu so it can become a link, pill, or bookmark.
      handlePaste: (view, event) => {
        const text = event.clipboardData?.getData('text/plain') ?? '';
        if (!/^https?:\/\/\S+$/i.test(text.trim())) return false;

        event.preventDefault();
        const { from } = view.state.selection;
        const instance = view.state.schema;
        if (!instance) return false;

        // Insert the URL as plain text, then offer the representations.
        view.dispatch(view.state.tr.insertText(text.trim(), from));
        const coords = view.coordsAtPos(from);
        const menuHeight = 150;
        const spaceBelow = window.innerHeight - coords.bottom;
        const top =
          spaceBelow < menuHeight && coords.top > spaceBelow ? coords.top - menuHeight - 8 : coords.bottom + 8;

        menusRef.current.setPasteMenu({
          url: text.trim(),
          position: from,
          coords: { left: coords.left, top },
        });
        return true;
      },
    },
  });

  // Lock only the editor's nearest scroll viewport while the slash menu is open. The document
  // remains scrollable elsewhere, and the fixed menu stays anchored during page scroll.
  useEffect(() => {
    if (!editor || !slash.props) return;
    const container = findScrollableAncestor(editor.view.dom);
    if (!container) return;
    const preventWheel = (event: WheelEvent) => event.preventDefault();
    container.addEventListener('wheel', preventWheel, { passive: false });
    return () => container.removeEventListener('wheel', preventWheel);
  }, [editor, slash.props]);

  // The image slash command signals through this editor's own Tiptap storage (storage mutations
  // are not tracked by React state), so register it while mounted. Keyed per editor, so two
  // editors on one page no longer clobber each other's image command.
  useEffect(() => {
    if (!editor) return;
    const instance = editor;
    registerImageInsertCallback(instance, (position) => {
      const coords = instance.view.coordsAtPos(position);
      const panelHeight = 480;
      const viewportGap = 16;
      const spaceBelow = window.innerHeight - coords.bottom;
      const preferredTop =
        spaceBelow < panelHeight && coords.top > spaceBelow ? coords.top - panelHeight - 8 : coords.bottom + 8;
      const top = Math.min(
        Math.max(preferredTop, viewportGap),
        Math.max(window.innerHeight - panelHeight - viewportGap, viewportGap),
      );
      setImageInput({ position, coords: { left: coords.left, top } });
    });
    return () => unregisterImageInsertCallback(instance);
  }, [editor]);

  useEffect(() => {
    if (!editor) return;
    const instance = editor;
    registerYouTubeInsertCallback(instance, (position) => {
      const coords = instance.view.coordsAtPos(position);
      setYouTubeInput({ position, coords: { left: coords.left, top: coords.bottom + 8 } });
    });
    return () => unregisterYouTubeInsertCallback(instance);
  }, [editor]);

  // The bookmark slash command writes a flag into editor.storage; poll it into React state.
  useEffect(() => {
    if (!editor) return;

    const sync = () => {
      // SAFETY: Tiptap storage is an open, untyped per-extension bag. The bookmark slash command
      // (in the framework-agnostic layer) writes this key and this effect is its only reader, so
      // there is no typed contract to rely on — the shape is asserted below by the guard.
      const storage = editor.storage as unknown as Record<string, unknown>;
      const flag = storage['bookmarkInput'] as { active?: boolean; position?: number } | undefined;
      if (flag?.active && typeof flag.position === 'number') {
        const position = flag.position;
        const coords = editor.view.coordsAtPos(position);
        setBookmarkInput({ position, coords: { left: coords.left, top: coords.bottom + 8 } });
        storage['bookmarkInput'] = { active: false };
      }
    };

    sync();
    editor.on('transaction', sync);
    return () => {
      editor.off('transaction', sync);
    };
  }, [editor]);

  useImperativeHandle(
    ref,
    () => ({
      focus: () => editor?.commands.focus('start'),
      updateContent: (json: string) => {
        if (editor && json !== JSON.stringify(editor.getJSON())) {
          try {
            editor.commands.setContent(JSON.parse(json));
          } catch (e) {
            console.error('Failed to parse content:', e);
          }
        }
      },
      getCounts: () => getEditorCounts(editor),
    }),
    [editor],
  );

  const closeMenus = useCallback(() => {
    setImageInput(null);
    setBookmarkInput(null);
    setPasteMenu(null);
  }, []);

  return (
    <div className="relative">
      <EditorContent editor={editor} />

      {editor ? <BubbleMenu editor={editor} /> : null}

      {editor && slash.props ? (
        <div className="fixed z-50" style={{ left: slash.coords.left, top: slash.coords.top }}>
          {/* slash.props is already SuggestionProps<SlashCommandItem> — spread it whole. */}
          <SlashMenu ref={slashRef} {...slash.props} />
        </div>
      ) : null}

      {editor && mention.props ? (
        <div className="fixed z-50" style={{ left: mention.coords.left, top: mention.coords.top }}>
          <MentionList ref={mentionRef} {...mention.props} />
        </div>
      ) : null}

      {editor && emoji.props ? (
        <div className="fixed z-50" style={{ left: emoji.coords.left, top: emoji.coords.top }}>
          <EmojiList ref={emojiRef} {...emoji.props} />
        </div>
      ) : null}

      {editor && imageInput ? (
        <div className="fixed z-50" style={{ left: imageInput.coords.left, top: imageInput.coords.top }}>
          <ImageInput
            editor={editor}
            position={imageInput.position}
            onUpload={onUpload}
            onClose={() => setImageInput(null)}
          />
        </div>
      ) : null}

      {editor && bookmarkInput ? (
        <div className="fixed z-50" style={{ left: bookmarkInput.coords.left, top: bookmarkInput.coords.top }}>
          <BookmarkInput editor={editor} position={bookmarkInput.position} onClose={() => setBookmarkInput(null)} />
        </div>
      ) : null}

      {editor && youTubeInput ? (
        <div className="fixed z-50" style={{ left: youTubeInput.coords.left, top: youTubeInput.coords.top }}>
          <YouTubeInput editor={editor} position={youTubeInput.position} onClose={() => setYouTubeInput(null)} />
        </div>
      ) : null}

      {editor && pasteMenu ? (
        <div className="fixed z-50" style={{ left: pasteMenu.coords.left, top: pasteMenu.coords.top }}>
          <PasteMenu editor={editor} url={pasteMenu.url} position={pasteMenu.position} onClose={closeMenus} />
        </div>
      ) : null}
    </div>
  );
});

function findScrollableAncestor(element: HTMLElement): HTMLElement | null {
  let current = element.parentElement;
  while (current && current !== document.body) {
    const overflowY = window.getComputedStyle(current).overflowY;
    if (/(auto|scroll)/.test(overflowY) && current.scrollHeight > current.clientHeight) return current;
    current = current.parentElement;
  }
  return null;
}

/** Build menu state with a flip-above-when-cramped position from the suggestion's rect. */
function menuFrom<T>(props: SuggestionProps<T>): MenuState<T> {
  const rect = props.clientRect?.();
  if (!rect) return { props, coords: { left: 0, top: 0 } };
  const menuHeight = 320;
  const spaceBelow = window.innerHeight - rect.bottom;
  const top = spaceBelow < menuHeight && rect.top > spaceBelow ? rect.top - menuHeight - 8 : rect.bottom + 8;
  return { props, coords: { left: rect.left, top } };
}
